language: cpp

sudo: required
dist: trusty

script: make test-debug

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - apokluda/boost1.53
          packages:
            - g++-4.8
            - libboost1.53-all-dev
      env: COMPILER=g++-4.8
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-5
            - libboost-all-dev
      env: COMPILER=g++-5
