language: cpp

compiler:
  - gcc
  - g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev
    - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
